import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;




/**
 *
 * @author thuhoang
 */
public class loginUI extends javax.swing.JFrame {

    /**
     * Creates new form loginUI
     */
    public loginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        uBox = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        //pBox.setEchoChar((char)0);
        pBox = new javax.swing.JPasswordField();
        showP = new javax.swing.JCheckBox();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        textD = new javax.swing.JLabel();
        textP = new javax.swing.JLabel();
        textM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setPreferredSize(new java.awt.Dimension(700, 430));

        mainPanel.setBackground(new java.awt.Color(169, 152, 152));
        mainPanel.setPreferredSize(new java.awt.Dimension(700, 420));
        mainPanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(237, 237, 239));

        title.setFont(new java.awt.Font("Gill Sans", 0, 34)); // NOI18N
        title.setForeground(new java.awt.Color(51, 51, 51));
        title.setText("Welcome back");

        loginbtn.setBackground(new java.awt.Color(51, 51, 51));
        loginbtn.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("LOGIN");
        loginbtn.setBorderPainted(false);
        loginbtn.setOpaque(true);
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        user.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(51, 51, 51));
        user.setText("Password:");

        uBox.setBackground(new java.awt.Color(237, 237, 239));
        uBox.setFont(new java.awt.Font("Gill Sans", 0, 16)); // NOI18N
        uBox.setForeground(new java.awt.Color(51, 51, 51));
        uBox.setText("Enter your username");
        uBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(226, 226, 226), new java.awt.Color(237, 237, 239)));
        uBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                uBoxFocusLost(evt);
            }
        });

        password.setFont(new java.awt.Font("Gill Sans", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(51, 51, 51));
        password.setText("Username:");

        pBox.setBackground(new java.awt.Color(237, 237, 239));
        pBox.setFont(new java.awt.Font("Gill Sans", 0, 16)); // NOI18N
        pBox.setForeground(new java.awt.Color(51, 51, 51));
        pBox.setText("Enter your password");
        pBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(226, 226, 226), new java.awt.Color(237, 237, 239)));
        pBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pBoxFocusLost(evt);
            }
        });
        pBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBoxActionPerformed(evt);
            }
        });

        showP.setFont(new java.awt.Font("Gill Sans", 0, 16)); // NOI18N
        showP.setText("Show password");
        showP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPActionPerformed(evt);
            }
        });

        textD.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
        textD.setText("D");

        textP.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
        textP.setText("P");

        textM.setFont(new java.awt.Font("Gill Sans", 1, 48)); // NOI18N
        textM.setText("M");

        jLayeredPane1.setLayer(textD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(textP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(textM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textM)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(textM))
                    .addComponent(textP)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(textD)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showP)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password)
                            .addComponent(uBox)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pBox, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(202, 202, 202))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261)
                .addComponent(jLayeredPane1)
                .addGap(193, 193, 193))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showP)
                .addGap(5, 5, 5)
                .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        mainPanel.add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPActionPerformed
        // TODO add your handling code here:
        if(showP.isSelected()){
            pBox.setEchoChar((char)0);
        } else {
            pBox.setEchoChar('●');
        }
    }//GEN-LAST:event_showPActionPerformed

    private void pBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pBoxActionPerformed

    private void pBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pBoxFocusLost
        // TODO add your handling code here:
        if(pBox.getPassword().length<1)
        {
            pBox.setEchoChar((char)0);
            pBox.setText("Enter your password");
            //            pBox.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_pBoxFocusLost

    private void pBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pBoxFocusGained
        // TODO add your handling code here:
        if(String.valueOf(pBox.getPassword()).equals("Enter your password"))
        {
            pBox.setText("");
            pBox.setForeground(new Color(51,51,51));
            pBox.setEchoChar('●');
        }
    }//GEN-LAST:event_pBoxFocusGained

    private void uBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uBoxFocusLost
        // TODO add your handling code here:
        if(uBox.getText().equals(""))
        {
            uBox.setText("Enter your username");
            uBox.setForeground(new Color(51,51,51));
            //            uBox.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_uBoxFocusLost

    private void uBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uBoxFocusGained
        // TODO add your handling code here:
        if(uBox.getText().equals("Enter your username"))
        {
            uBox.setText("");
            uBox.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_uBoxFocusGained

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:'

        String username = uBox.getText();
        String pw = String.valueOf(pBox.getPassword());

        //        if (password.equals("123") && (username.equals("keke")))
        //        {
            ////            username.setText(null);
            ////            password.setText(null);
            //           // systemExit();
            //
            //
            //            homeUI frame = new homeUI();
            //            frame.setVisible(true);
            //            this.dispose();
            //        } else

        // tam cmt below one
                if(username == null || pw == null) {
                        JOptionPane.showMessageDialog(null,"Empty Login Details");
                        uBox.setText(null); // same result w ""
                        pBox.setText(null);
                    } else {
                    
                         String jdbc = "jdbc:sqlserver://localhost:1433;databaseName=Movie_Booking_System;encrypt=true;trustServerCertificate=true;user=sa;password=dockerStrongPwd123";
            
                        try{
                
                                Connection con = DriverManager.getConnection(jdbc);
                                
                                // NHO DOI TEN DATABASE VA TABLE_NAME (username and pw)
                                String sqlquery = "SELECT * FROM Customer WHERE cId = '" + username + "'AND cPassword = '" + pw + "'";
                
                                PreparedStatement pst = con.prepareStatement(sqlquery);
                                ResultSet rs = pst.executeQuery();
                
                                if (rs.next()) {
                                        JOptionPane.showMessageDialog(null, "Login Successfully!");
                                        homeUI home = new homeUI();
                                        home.setVisible(true);
                                        home.pack();
                                        home.setLocationRelativeTo(null);
                                        this.dispose();
                                    } else {
                                    // Invalid credentials
                                        JOptionPane.showMessageDialog(null, "Incorrect Username/Password!");
                                        uBox.setText("");
                                        pBox.setText("");
                                    }
                            } catch (Exception e){
                                e.printStackTrace();
                            }
                    }
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new loginUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField pBox;
    private javax.swing.JLabel password;
    private javax.swing.JCheckBox showP;
    private javax.swing.JLabel textD;
    private javax.swing.JLabel textM;
    private javax.swing.JLabel textP;
    private javax.swing.JLabel title;
    private javax.swing.JTextField uBox;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables


    
    
}
