/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author DELL
 */
public class Movie extends javax.swing.JFrame {

    /**
     * Creates new form Movie
     */
    public Movie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chiemdoat = new javax.swing.JButton();
        duongcung = new javax.swing.JButton();
        taylorswift = new javax.swing.JButton();
        phuongnam = new javax.swing.JButton();
        aquaman = new javax.swing.JButton();
        yeulaivongau = new javax.swing.JButton();
        avatar = new javax.swing.JButton();
        wonka = new javax.swing.JButton();
        teeyod = new javax.swing.JButton();
        ont = new javax.swing.JButton();
        dieuuoc = new javax.swing.JButton();
        ghilbli = new javax.swing.JButton();

        jButton11.setText("jButton1");

        jButton7.setText("jButton1");

        jButton9.setText("jButton1");

        jButton12.setText("jButton1");

        jButton8.setText("jButton1");

        jButton10.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MOVIE");

        chiemdoat.setText("CHIEM DOAT ");
        chiemdoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiemdoatActionPerformed(evt);
            }
        });

        duongcung.setText("DUONG CUNG");
        duongcung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duongcungActionPerformed(evt);
            }
        });

        taylorswift.setText("NHUNG KY NGUYEN CUA TAYLOR SWIFT");
        taylorswift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taylorswiftActionPerformed(evt);
            }
        });

        phuongnam.setText("DAT RUNG PHUONG NAM");
        phuongnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phuongnamActionPerformed(evt);
            }
        });

        aquaman.setText("AQUAMAN VA VUONG QUOC THAT LAC");
        aquaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aquamanActionPerformed(evt);
            }
        });

        yeulaivongau.setText("YEU LAI VO NGAU");
        yeulaivongau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeulaivongauActionPerformed(evt);
            }
        });

        avatar.setText("AVATAR: DONG CHAY CUA NUOC");
        avatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarActionPerformed(evt);
            }
        });

        wonka.setText("WONKA");
        wonka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wonkaActionPerformed(evt);
            }
        });

        teeyod.setText("TEE YOD: QUY AN TANG");
        teeyod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teeyodActionPerformed(evt);
            }
        });

        ont.setText("MOT MINH VAN ON\"T");
        ont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ontActionPerformed(evt);
            }
        });

        dieuuoc.setText("DIEU UOC");
        dieuuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieuuocActionPerformed(evt);
            }
        });

        ghilbli.setText("THIEU NIEN VA CHIM DIEC");
        ghilbli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghilbliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aquaman, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phuongnam, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yeulaivongau, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taylorswift, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duongcung, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chiemdoat, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dieuuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ont, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ghilbli, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wonka, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teeyod, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chiemdoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(duongcung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taylorswift, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yeulaivongau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phuongnam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aquaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teeyod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wonka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ghilbli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ont, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dieuuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chiemdoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiemdoatActionPerformed
        this.hide();
        new ChiemDoat().show();        
    }//GEN-LAST:event_chiemdoatActionPerformed

    private void duongcungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duongcungActionPerformed
        this.hide();
        new DuongCung().show(); // TODO add your handling code here:
    }//GEN-LAST:event_duongcungActionPerformed

    private void taylorswiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taylorswiftActionPerformed
        this.hide();
        new TaylorSwift().show();        // TODO add your handling code here:
    }//GEN-LAST:event_taylorswiftActionPerformed

    private void yeulaivongauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeulaivongauActionPerformed
        this.hide();
        new VoNgau().show();        // TODO add your handling code here:
    }//GEN-LAST:event_yeulaivongauActionPerformed

    private void phuongnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phuongnamActionPerformed
        this.hide();
        new PhuongNam().show();        // TODO add your handling code here:
    }//GEN-LAST:event_phuongnamActionPerformed

    private void aquamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aquamanActionPerformed
        this.hide();
        new Aquaman().show();        // TODO add your handling code here:
    }//GEN-LAST:event_aquamanActionPerformed

    private void teeyodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teeyodActionPerformed
        this.hide();
        new TeeYod().show();        // TODO add your handling code here:
    }//GEN-LAST:event_teeyodActionPerformed

    private void avatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarActionPerformed
        this.hide();
        new Avatar().show();        // TODO add your handling code here:
    }//GEN-LAST:event_avatarActionPerformed

    private void wonkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wonkaActionPerformed
        this.hide();
        new Wonka().show();        // TODO add your handling code here:
    }//GEN-LAST:event_wonkaActionPerformed

    private void ghilbliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghilbliActionPerformed
        this.hide();
        new ThieuNien().show();        // TODO add your handling code here:
    }//GEN-LAST:event_ghilbliActionPerformed

    private void ontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ontActionPerformed
        this.hide();
        new MotMinhVanOn().show();        // TODO add your handling code here:
    }//GEN-LAST:event_ontActionPerformed

    private void dieuuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieuuocActionPerformed
        this.hide();
        new DieuUoc().show();        // TODO add your handling code here:
    }//GEN-LAST:event_dieuuocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Movie frame = new Movie();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);  // appear center the screen
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aquaman;
    private javax.swing.JButton avatar;
    private javax.swing.JButton chiemdoat;
    private javax.swing.JButton dieuuoc;
    private javax.swing.JButton duongcung;
    private javax.swing.JButton ghilbli;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ont;
    private javax.swing.JButton phuongnam;
    private javax.swing.JButton taylorswift;
    private javax.swing.JButton teeyod;
    private javax.swing.JButton wonka;
    private javax.swing.JButton yeulaivongau;
    // End of variables declaration//GEN-END:variables
}
